### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by lzzy12** [TeamButter/android_hardware_samsung_sprd#1]
Hey there, while building this, I am getting this error
https://hastebin.com/tadufecusi.pas
Any help on this??

**Comment by Lehkeda** [comment]
@lzzy12 sorry, I've just noticed your issue.
what branch are you using ?

**Comment by lzzy12** [comment]
Cm-14.1

**Comment by Lehkeda** [comment]
@lzzy12  apply this commit https://github.com/TeamButter/android_hardware_samsung_sprd/commit/c993c5c8f15eb0638d17722d2b4abcb6d467b618 and try again

**Comment by remilia15** [comment]
@Lehkeda have you guys started O?
I'm working on it with my GPVE now. Got stuck on Sammy logo o.O

**Comment by Lehkeda** [comment]
@remilia15 same here I couldn't pass bootlogo 
I've tried patching kernel binder but I think it doesn't work.
BTW, did you patch system/init ?

**Comment by remilia15** [comment]
Yeah, some repopicks from @nikitsharma15 :v

**Comment by halfpsych** [comment]
This issue has been fixed in https://github.com/TeamButter/android_hardware_samsung_sprd/commit/09bcb80d26aa5ebfc02c4bc973b9c0efda19c4ba 

I guess we can create another issue in about Oreo or perhaps a channel in Gitter.

Closing this for now.
